name: Check TMDB IP

on:
  schedule:
    - cron: '0 3,18 * * *'  # 每天 3:00 和 18:00 执行
  workflow_dispatch:
    inputs:
      debug-enabled:
        description: '是否启用调试模式'
        required: false
        default: 'false'
        type: boolean
      force-update:
        description: '强制更新 IP（即使没有变化）'
        required: false
        default: 'false'
        type: boolean

jobs:
  check-tmdb:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then sudo pip install -r requirements.txt; fi
    - name: Run check script
      run: |
        sudo python check_tmdb_github.py
    - name: Commit changes
      id: commit
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'lostwikee@gmail.com'
        git add README.md Tmdb_host
        git commit -m "Update TMDB IP [skip ci]"
      continue-on-error: true
    - name: Check on failures
      if: steps.commit.outputs.status == 'failure'
      run: exit 1
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
