name: Check TMDB IP

on:
  schedule:
    - cron: '0 3,18 * * *'  # 每天 3:00 和 18:00 执行
  workflow_dispatch:  # 允许手动触发

jobs:
  check-tmdb:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run check script
      run: |
        python check_tmdb_github.py
        
    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'lostwikee@gmail.com'
        git add README.md Tmdb_host
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update TMDB IP [skip ci]" && git push)
