name: Check TMDB IP

on:
  schedule:
    - cron: '0 6,18 * * *'  # 每天 6:00 和 18:00 执行
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        sudo python -m pip install --upgrade pip
        sudo pip install -r requirements.txt
        
    - name: Run Python script
      run: |
        sudo python check_tmdb_github.py
        
    - name: Commit 和 push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'lostwikee@gmail.com'
        git add README.md Tmdb_host
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update TMDB IP [skip ci]" && git push)
