name: Check TMDB IP

on:
  schedule:
    - cron: '0 6,18 * * *'  # 每天 6:00 和 18:00 执行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        sudo python -m pip install --upgrade pip
        sudo pip install -r requirements.txt
        
    - name: Run Python script
      run: |
        sudo python check_tmdb_github.py
        
    - name: 提交更改
      run: |
         git config --global user.name 'GitHub Action'
         git config --global user.email 'lostwikee@gmail.com'
         git add .
         git commit -m "Update TMDB IP [skip ci]" || echo "No changes to commit"
      continue-on-error: true

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
