name: Check TMDB IP

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6,18 * * *'  # 每天 6:00 和 18:00 执行

permissions:
  contents: write  # 确保有写入权限

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        sudo python -m pip install --upgrade pip
        sudo pip install -r requirements.txt
        
    - name: Run Python script
      run: |
        sudo python check_tmdb.py
        
    - name: 提交更改
      run: |
         git config --global user.name 'GitHub Action'
         git config --global user.email 'action@github.com'
         git add README.md Tmdb_host
         git commit -m "Update TMDB IP [action]" || echo "No changes to commit"
      continue-on-error: true

    - name: Push changes
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: git push origin main
